version: '3.8'

services:
  mapping-service:
    image: vitalie97/mapping-service-backend:latest
    ports:
      - "8095:8095"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s

  initializer:
    image: vitalie97/mapping-service-initializer:latest
    depends_on:
      mapping-service:
        condition: service_healthy

  frontend:
    image: vitalie97/mapping-service-frontend:latest
    ports:
      - "80:80"
    depends_on:
      mapping-service:
        condition: service_healthy
